export const manClothes = {
  tshirts: [
    {
      id: "mt1",
      title: "blue nike t-shirt (mt1)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 167.68,
      brand: "nike",
      color: "blue",
      photo: "manshirt1",
      onSale: false,
    },
    {
      id: "mt2",
      title: "blue nike t-shirt (mt2)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 190.44,
      brand: "nike",
      color: "blue",
      photo: "manshirt2",
      onSale: false,
    },
    {
      id: "mt3",
      title: "blue nike t-shirt (mt3)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 183.06,
      brand: "nike",
      color: "blue",
      photo: "manshirt3",
      onSale: false,
    },
    {
      id: "mt4",
      title: "red nike t-shirt (mt4)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 166.08,
      brand: "nike",
      color: "red",
      photo: "manshirt4",
      onSale: false,
    },
    {
      id: "mt5",
      title: "red nike t-shirt (mt5)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 133.52,
      brand: "nike",
      color: "red",
      photo: "manshirt5",
      onSale: false,
    },
    {
      id: "mt6",
      title: "yellow nike t-shirt (mt6)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 61.45,
      brand: "nike",
      color: "yellow",
      photo: "manshirt6",
      onSale: false,
    },
    {
      id: "mt7",
      title: "green nike t-shirt (mt7)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 226.62,
      brand: "nike",
      color: "green",
      photo: "manshirt7",
      onSale: false,
    },
    {
      id: "mt8",
      title: "red nike t-shirt (mt8)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 184.55,
      brand: "nike",
      color: "red",
      photo: "manshirt8",
      onSale: false,
    },
    {
      id: "mt9",
      title: "green nike t-shirt (mt9)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 294.34,
      brand: "nike",
      color: "green",
      photo: "manshirt9",
      onSale: false,
    },
    {
      id: "mt10",
      title: "green nike t-shirt (mt10)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 132.92,
      brand: "nike",
      color: "green",
      photo: "manshirt10",
      onSale: false,
    },
    {
      id: "mt11",
      title: "yellow nike t-shirt (mt11)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 239.33,
      brand: "nike",
      color: "yellow",
      photo: "manshirt11",
      onSale: false,
    },
    {
      id: "mt12",
      title: "yellow nike t-shirt (mt12)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 201.39,
      brand: "nike",
      color: "yellow",
      photo: "manshirt12",
      onSale: true,
    },
    {
      id: "mt13",
      title: "yellow adidas t-shirt (mt13)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 57.65,
      brand: "adidas",
      color: "yellow",
      photo: "manshirt13",
      onSale: false,
    },
    {
      id: "mt14",
      title: "yellow adidas t-shirt (mt14)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 297.48,
      brand: "adidas",
      color: "yellow",
      photo: "manshirt14",
      onSale: false,
    },
    {
      id: "mt15",
      title: "yellow adidas t-shirt (mt15)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 237.03,
      brand: "adidas",
      color: "yellow",
      photo: "manshirt15",
      onSale: false,
    },
    {
      id: "mt16",
      title: "red adidas t-shirt (mt16)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 290.71,
      brand: "adidas",
      color: "red",
      photo: "manshirt16",
      onSale: false,
    },
    {
      id: "mt17",
      title: "red adidas t-shirt (mt17)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 184.51,
      brand: "adidas",
      color: "red",
      photo: "manshirt17",
      onSale: false,
    },
    {
      id: "mt18",
      title: "red adidas t-shirt (mt18)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 37.78,
      brand: "adidas",
      color: "red",
      photo: "manshirt18",
      onSale: false,
    },
    {
      id: "mt19",
      title: "blue adidas t-shirt (mt19)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 35.48,
      brand: "adidas",
      color: "blue",
      photo: "manshirt19",
      onSale: true,
    },
    {
      id: "mt20",
      title: "blue adidas t-shirt (mt20)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 218.53,
      brand: "adidas",
      color: "blue",
      photo: "manshirt20",
      onSale: false,
    },
    {
      id: "mt21",
      title: "blue adidas t-shirt (mt21)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 158.59,
      brand: "adidas",
      color: "blue",
      photo: "manshirt21",
      onSale: false,
    },
    {
      id: "mt22",
      title: "green adidas t-shirt (mt22)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 285.56,
      brand: "adidas",
      color: "green",
      photo: "manshirt22",
      onSale: false,
    },
    {
      id: "mt23",
      title: "green adidas t-shirt (mt23)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 201.55,
      brand: "adidas",
      color: "green",
      photo: "manshirt23",
      onSale: false,
    },
    {
      id: "mt24",
      title: "green adidas t-shirt (mt24)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 207.48,
      brand: "adidas",
      color: "green",
      photo: "manshirt24",
      onSale: false,
    },
    {
      id: "mt25",
      title: "green reebok t-shirt (mt25)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 240.95,
      brand: "reebok",
      color: "green",
      photo: "manshirt25",
      onSale: false,
    },
    {
      id: "mt26",
      title: "green reebok t-shirt (mt26)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 222.05,
      brand: "reebok",
      color: "green",
      photo: "manshirt26",
      onSale: false,
    },
    {
      id: "mt27",
      title: "green reebok t-shirt (mt27)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 156.29,
      brand: "reebok",
      color: "green",
      photo: "manshirt27",
      onSale: true,
    },
    {
      id: "mt28",
      title: "red reebok t-shirt (mt28)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 59.95,
      brand: "reebok",
      color: "red",
      photo: "manshirt28",
      onSale: false,
    },
    {
      id: "mt29",
      title: "red reebok t-shirt (mt29)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 56.21,
      brand: "reebok",
      color: "red",
      photo: "manshirt29",
      onSale: false,
    },
    {
      id: "mt30",
      title: "red reebok t-shirt (mt30)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 70.18,
      brand: "reebok",
      color: "red",
      photo: "manshirt30",
      onSale: false,
    },
    {
      id: "mt31",
      title: "blue reebok t-shirt (mt31)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 101.0,
      brand: "reebok",
      color: "blue",
      photo: "manshirt31",
      onSale: false,
    },
    {
      id: "mt32",
      title: "blue reebok t-shirt (mt32)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 36.97,
      brand: "reebok",
      color: "blue",
      photo: "manshirt32",
      onSale: false,
    },
    {
      id: "mt33",
      title: "blue reebok t-shirt (mt33)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 119.11,
      brand: "reebok",
      color: "blue",
      photo: "manshirt33",
      onSale: false,
    },
    {
      id: "mt34",
      title: "yellow reebok t-shirt (mt34)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 237.04,
      brand: "reebok",
      color: "yellow",
      photo: "manshirt34",
      onSale: false,
    },
    {
      id: "mt35",
      title: "yellow reebok t-shirt (mt35)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 196.51,
      brand: "reebok",
      color: "yellow",
      photo: "manshirt35",
      onSale: false,
    },
    {
      id: "mt36",
      title: "yellow reebok t-shirt (mt36)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 108.72,
      brand: "reebok",
      color: "yellow",
      photo: "manshirt36",
      onSale: false,
    },
    {
      id: "mt37",
      title: "yellow puma t-shirt (mt37)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 177.81,
      brand: "puma",
      color: "yellow",
      photo: "manshirt37",
      onSale: false,
    },
    {
      id: "mt38",
      title: "yellow puma t-shirt (mt38)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 244.48,
      brand: "puma",
      color: "yellow",
      photo: "manshirt38",
      onSale: false,
    },
    {
      id: "mt39",
      title: "yellow puma t-shirt (mt39)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 76.68,
      brand: "puma",
      color: "yellow",
      photo: "manshirt39",
      onSale: false,
    },
    {
      id: "mt40",
      title: "green puma t-shirt (mt40)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 168.12,
      brand: "puma",
      color: "green",
      photo: "manshirt40",
      onSale: false,
    },
    {
      id: "mt41",
      title: "green puma t-shirt (mt41)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 141.92,
      brand: "puma",
      color: "green",
      photo: "manshirt41",
      onSale: false,
    },
    {
      id: "mt42",
      title: "red puma t-shirt (mt42)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 170.41,
      brand: "puma",
      color: "red",
      photo: "manshirt42",
      onSale: false,
    },
    {
      id: "mt43",
      title: "green puma t-shirt (mt43)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 42.37,
      brand: "puma",
      color: "green",
      photo: "manshirt43",
      onSale: false,
    },
    {
      id: "mt44",
      title: "blue puma t-shirt (mt44)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 152.99,
      brand: "puma",
      color: "blue",
      photo: "manshirt44",
      onSale: false,
    },
    {
      id: "mt45",
      title: "blue puma t-shirt (mt45)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 116.35,
      brand: "puma",
      color: "blue",
      photo: "manshirt45",
      onSale: false,
    },
    {
      id: "mt46",
      title: "blue puma t-shirt (mt46)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 79.18,
      brand: "puma",
      color: "blue",
      photo: "manshirt46",
      onSale: false,
    },
    {
      id: "mt47",
      title: "red puma t-shirt (mt47)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 74.15,
      brand: "puma",
      color: "red",
      photo: "manshirt47",
      onSale: false,
    },
    {
      id: "mt48",
      title: "red puma t-shirt (mt48)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 111.66,
      brand: "puma",
      color: "red",
      photo: "manshirt48",
      onSale: false,
    },
  ],
  pants: [
    {
      id: "mp1",
      title: "yellow adidas pants (mp1)",
      desc:
        "Featuring a flattering, slim fit, these trousers have just the right amount of stretch in the fabric to avoid feeling like a stuffed sausage. Available in several colorways, you can stock your whole closet with this perfect pant for spring.",
      price: 244.56,
      brand: "adidas",
      color: "yellow",
      photo: "manpants1",
      onSale: false,
    },
    {
      id: "mp2",
      title: "yellow adidas pants (mp2)",
      desc:
        "Featuring a flattering, slim fit, these trousers have just the right amount of stretch in the fabric to avoid feeling like a stuffed sausage. Available in several colorways, you can stock your whole closet with this perfect pant for spring.",
      price: 229.86,
      brand: "adidas",
      color: "yellow",
      photo: "manpants2",
      onSale: true,
    },
    {
      id: "mp3",
      title: "yellow adidas pants (mp3)",
      desc:
        "Featuring a flattering, slim fit, these trousers have just the right amount of stretch in the fabric to avoid feeling like a stuffed sausage. Available in several colorways, you can stock your whole closet with this perfect pant for spring.",
      price: 87.21,
      brand: "adidas",
      color: "yellow",
      photo: "manpants3",
      onSale: false,
    },
    {
      id: "mp4",
      title: "blue adidas pants (mp4)",
      desc:
        "Featuring a flattering, slim fit, these trousers have just the right amount of stretch in the fabric to avoid feeling like a stuffed sausage. Available in several colorways, you can stock your whole closet with this perfect pant for spring.",
      price: 188.06,
      brand: "adidas",
      color: "blue",
      photo: "manpants4",
      onSale: false,
    },
    {
      id: "mp5",
      title: "blue adidas pants (mp5)",
      desc:
        "Featuring a flattering, slim fit, these trousers have just the right amount of stretch in the fabric to avoid feeling like a stuffed sausage. Available in several colorways, you can stock your whole closet with this perfect pant for spring.",
      price: 269.05,
      brand: "adidas",
      color: "blue",
      photo: "manpants5",
      onSale: false,
    },
    {
      id: "mp6",
      title: "blue adidas pants (mp6)",
      desc:
        "Featuring a flattering, slim fit, these trousers have just the right amount of stretch in the fabric to avoid feeling like a stuffed sausage. Available in several colorways, you can stock your whole closet with this perfect pant for spring.",
      price: 219.33,
      brand: "adidas",
      color: "blue",
      photo: "manpants6",
      onSale: false,
    },
    {
      id: "mp7",
      title: "red adidas pants (mp7)",
      desc:
        "Featuring a flattering, slim fit, these trousers have just the right amount of stretch in the fabric to avoid feeling like a stuffed sausage. Available in several colorways, you can stock your whole closet with this perfect pant for spring.",
      price: 47.72,
      brand: "adidas",
      color: "red",
      photo: "manpants7",
      onSale: true,
    },
    {
      id: "mp8",
      title: "red adidas pants (mp8)",
      desc:
        "Featuring a flattering, slim fit, these trousers have just the right amount of stretch in the fabric to avoid feeling like a stuffed sausage. Available in several colorways, you can stock your whole closet with this perfect pant for spring.",
      price: 63.44,
      brand: "adidas",
      color: "red",
      photo: "manpants8",
      onSale: false,
    },
    {
      id: "mp9",
      title: "red adidas pants (mp9)",
      desc:
        "Featuring a flattering, slim fit, these trousers have just the right amount of stretch in the fabric to avoid feeling like a stuffed sausage. Available in several colorways, you can stock your whole closet with this perfect pant for spring.",
      price: 48.41,
      brand: "adidas",
      color: "red",
      photo: "manpants9",
      onSale: true,
    },
    {
      id: "mp10",
      title: "green adidas pants (mp10)",
      desc:
        "Featuring a flattering, slim fit, these trousers have just the right amount of stretch in the fabric to avoid feeling like a stuffed sausage. Available in several colorways, you can stock your whole closet with this perfect pant for spring.",
      price: 287.49,
      brand: "adidas",
      color: "green",
      photo: "manpants10",
      onSale: false,
    },
    {
      id: "mp11",
      title: "green adidas pants (mp11)",
      desc:
        "Featuring a flattering, slim fit, these trousers have just the right amount of stretch in the fabric to avoid feeling like a stuffed sausage. Available in several colorways, you can stock your whole closet with this perfect pant for spring.",
      price: 97.31,
      brand: "adidas",
      color: "green",
      photo: "manpants11",
      onSale: true,
    },
    {
      id: "mp12",
      title: "green adidas pants (mp12)",
      desc:
        "Featuring a flattering, slim fit, these trousers have just the right amount of stretch in the fabric to avoid feeling like a stuffed sausage. Available in several colorways, you can stock your whole closet with this perfect pant for spring.",
      price: 173.76,
      brand: "adidas",
      color: "green",
      photo: "manpants12",
      onSale: false,
    },
    {
      id: "mp13",
      title: "green nike pants (mp13)",
      desc:
        "Featuring a flattering, slim fit, these trousers have just the right amount of stretch in the fabric to avoid feeling like a stuffed sausage. Available in several colorways, you can stock your whole closet with this perfect pant for spring.",
      price: 289.86,
      brand: "nike",
      color: "green",
      photo: "manpants13",
      onSale: false,
    },
    {
      id: "mp14",
      title: "green nike pants (mp14)",
      desc:
        "Featuring a flattering, slim fit, these trousers have just the right amount of stretch in the fabric to avoid feeling like a stuffed sausage. Available in several colorways, you can stock your whole closet with this perfect pant for spring.",
      price: 52.28,
      brand: "nike",
      color: "green",
      photo: "manpants14",
      onSale: false,
    },
    {
      id: "mp15",
      title: "green nike pants (mp15)",
      desc:
        "Featuring a flattering, slim fit, these trousers have just the right amount of stretch in the fabric to avoid feeling like a stuffed sausage. Available in several colorways, you can stock your whole closet with this perfect pant for spring.",
      price: 288.58,
      brand: "nike",
      color: "green",
      photo: "manpants15",
      onSale: false,
    },
    {
      id: "mp16",
      title: "yellow nike pants (mp16)",
      desc:
        "Featuring a flattering, slim fit, these trousers have just the right amount of stretch in the fabric to avoid feeling like a stuffed sausage. Available in several colorways, you can stock your whole closet with this perfect pant for spring.",
      price: 97.74,
      brand: "nike",
      color: "yellow",
      photo: "manpants16",
      onSale: false,
    },
    {
      id: "mp17",
      title: "yellow nike pants (mp17)",
      desc:
        "Featuring a flattering, slim fit, these trousers have just the right amount of stretch in the fabric to avoid feeling like a stuffed sausage. Available in several colorways, you can stock your whole closet with this perfect pant for spring.",
      price: 291.89,
      brand: "nike",
      color: "yellow",
      photo: "manpants17",
      onSale: false,
    },
    {
      id: "mp18",
      title: "yellow nike pants (mp18)",
      desc:
        "Featuring a flattering, slim fit, these trousers have just the right amount of stretch in the fabric to avoid feeling like a stuffed sausage. Available in several colorways, you can stock your whole closet with this perfect pant for spring.",
      price: 34.32,
      brand: "nike",
      color: "yellow",
      photo: "manpants18",
      onSale: false,
    },
    {
      id: "mp19",
      title: "red nike pants (mp19)",
      desc:
        "Featuring a flattering, slim fit, these trousers have just the right amount of stretch in the fabric to avoid feeling like a stuffed sausage. Available in several colorways, you can stock your whole closet with this perfect pant for spring.",
      price: 136.08,
      brand: "nike",
      color: "red",
      photo: "manpants19",
      onSale: false,
    },
    {
      id: "mp20",
      title: "red reebok pants (mp20)",
      desc:
        "Featuring a flattering, slim fit, these trousers have just the right amount of stretch in the fabric to avoid feeling like a stuffed sausage. Available in several colorways, you can stock your whole closet with this perfect pant for spring.",
      price: 128.65,
      brand: "reebok",
      color: "red",
      photo: "manpants20",
      onSale: true,
    },
    {
      id: "mp21",
      title: "blue reebok pants (mp21)",
      desc:
        "Featuring a flattering, slim fit, these trousers have just the right amount of stretch in the fabric to avoid feeling like a stuffed sausage. Available in several colorways, you can stock your whole closet with this perfect pant for spring.",
      price: 70.28,
      brand: "reebok",
      color: "blue",
      photo: "manpants21",
      onSale: false,
    },
    {
      id: "mp22",
      title: "blue reebok pants (mp22)",
      desc:
        "Featuring a flattering, slim fit, these trousers have just the right amount of stretch in the fabric to avoid feeling like a stuffed sausage. Available in several colorways, you can stock your whole closet with this perfect pant for spring.",
      price: 297.66,
      brand: "reebok",
      color: "blue",
      photo: "manpants22",
      onSale: true,
    },
    {
      id: "mp23",
      title: "yellow reebok pants (mp23)",
      desc:
        "Featuring a flattering, slim fit, these trousers have just the right amount of stretch in the fabric to avoid feeling like a stuffed sausage. Available in several colorways, you can stock your whole closet with this perfect pant for spring.",
      price: 198.98,
      brand: "reebok",
      color: "yellow",
      photo: "manpants23",
      onSale: false,
    },
    {
      id: "mp24",
      title: "blue reebok pants (mp24)",
      desc:
        "Featuring a flattering, slim fit, these trousers have just the right amount of stretch in the fabric to avoid feeling like a stuffed sausage. Available in several colorways, you can stock your whole closet with this perfect pant for spring.",
      price: 101.76,
      brand: "reebok",
      color: "blue",
      photo: "manpants24",
      onSale: false,
    },
    {
      id: "mp25",
      title: "red reebok pants (mp25)",
      desc:
        "Featuring a flattering, slim fit, these trousers have just the right amount of stretch in the fabric to avoid feeling like a stuffed sausage. Available in several colorways, you can stock your whole closet with this perfect pant for spring.",
      price: 144.09,
      brand: "reebok",
      color: "red",
      photo: "manpants25",
      onSale: true,
    },
    {
      id: "mp26",
      title: "green puma pants (mp26)",
      desc:
        "Featuring a flattering, slim fit, these trousers have just the right amount of stretch in the fabric to avoid feeling like a stuffed sausage. Available in several colorways, you can stock your whole closet with this perfect pant for spring.",
      price: 69.51,
      brand: "puma",
      color: "green",
      photo: "manpants26",
      onSale: false,
    },
    {
      id: "mp27",
      title: "blue puma pants (mp27)",
      desc:
        "Featuring a flattering, slim fit, these trousers have just the right amount of stretch in the fabric to avoid feeling like a stuffed sausage. Available in several colorways, you can stock your whole closet with this perfect pant for spring.",
      price: 263.27,
      brand: "puma",
      color: "blue",
      photo: "manpants27",
      onSale: false,
    },
    {
      id: "mp28",
      title: "green puma pants (mp28)",
      desc:
        "Featuring a flattering, slim fit, these trousers have just the right amount of stretch in the fabric to avoid feeling like a stuffed sausage. Available in several colorways, you can stock your whole closet with this perfect pant for spring.",
      price: 260.79,
      brand: "puma",
      color: "green",
      photo: "manpants28",
      onSale: false,
    },
  ],
  shoes: [
    {
      id: "ms1",
      title: "blue nike shoes (ms1)",
      desc:
        "The original sneakers come in a minimalist, leather silhouette resting on a rubber sole and are finished with the brand's signature coding on the outer sides.",
      price: 139.24,
      brand: "nike",
      color: "blue",
      photo: "manshoes1",
      onSale: false,
    },
    {
      id: "ms2",
      title: "blue nike shoes (ms2)",
      desc:
        "The original sneakers come in a minimalist, leather silhouette resting on a rubber sole and are finished with the brand's signature coding on the outer sides.",
      price: 226.89,
      brand: "nike",
      color: "blue",
      photo: "manshoes2",
      onSale: true,
    },
    {
      id: "ms3",
      title: "blue nike shoes (ms3)",
      desc:
        "The original sneakers come in a minimalist, leather silhouette resting on a rubber sole and are finished with the brand's signature coding on the outer sides.",
      price: 218.99,
      brand: "nike",
      color: "blue",
      photo: "manshoes3",
      onSale: false,
    },
    {
      id: "ms4",
      title: "yellow nike shoes (ms4)",
      desc:
        "The original sneakers come in a minimalist, leather silhouette resting on a rubber sole and are finished with the brand's signature coding on the outer sides.",
      price: 36.32,
      brand: "nike",
      color: "yellow",
      photo: "manshoes4",
      onSale: false,
    },
    {
      id: "ms5",
      title: "red nike shoes (ms5)",
      desc:
        "The original sneakers come in a minimalist, leather silhouette resting on a rubber sole and are finished with the brand's signature coding on the outer sides.",
      price: 160.43,
      brand: "nike",
      color: "red",
      photo: "manshoes5",
      onSale: false,
    },
    {
      id: "ms6",
      title: "red nike shoes (ms6)",
      desc:
        "The original sneakers come in a minimalist, leather silhouette resting on a rubber sole and are finished with the brand's signature coding on the outer sides.",
      price: 202.51,
      brand: "nike",
      color: "red",
      photo: "manshoes6",
      onSale: false,
    },
    {
      id: "ms7",
      title: "green nike shoes (ms7)",
      desc:
        "The original sneakers come in a minimalist, leather silhouette resting on a rubber sole and are finished with the brand's signature coding on the outer sides.",
      price: 59.05,
      brand: "nike",
      color: "green",
      photo: "manshoes7",
      onSale: true,
    },
    {
      id: "ms8",
      title: "blue reebok shoes (ms8)",
      desc:
        "The original sneakers come in a minimalist, leather silhouette resting on a rubber sole and are finished with the brand's signature coding on the outer sides.",
      price: 45.78,
      brand: "reebok",
      color: "blue",
      photo: "manshoes8",
      onSale: false,
    },
    {
      id: "ms9",
      title: "yellow reebok shoes (ms9)",
      desc:
        "The original sneakers come in a minimalist, leather silhouette resting on a rubber sole and are finished with the brand's signature coding on the outer sides.",
      price: 151.81,
      brand: "reebok",
      color: "yellow",
      photo: "manshoes9",
      onSale: false,
    },
    {
      id: "ms10",
      title: "blue reebok shoes (ms10)",
      desc:
        "The original sneakers come in a minimalist, leather silhouette resting on a rubber sole and are finished with the brand's signature coding on the outer sides.",
      price: 155.72,
      brand: "reebok",
      color: "blue",
      photo: "manshoes10",
      onSale: false,
    },
    {
      id: "ms11",
      title: "red reebok shoes (ms11)",
      desc:
        "The original sneakers come in a minimalist, leather silhouette resting on a rubber sole and are finished with the brand's signature coding on the outer sides.",
      price: 67.53,
      brand: "reebok",
      color: "red",
      photo: "manshoes11",
      onSale: false,
    },
    {
      id: "ms12",
      title: "red reebok shoes (ms12)",
      desc:
        "The original sneakers come in a minimalist, leather silhouette resting on a rubber sole and are finished with the brand's signature coding on the outer sides.",
      price: 276.09,
      brand: "reebok",
      color: "red",
      photo: "manshoes12",
      onSale: true,
    },
    {
      id: "ms13",
      title: "red adidas shoes (ms13)",
      desc:
        "The original sneakers come in a minimalist, leather silhouette resting on a rubber sole and are finished with the brand's signature coding on the outer sides.",
      price: 192.03,
      brand: "adidas",
      color: "red",
      photo: "manshoes13",
      onSale: false,
    },
    {
      id: "ms14",
      title: "yellow adidas shoes (ms14)",
      desc:
        "The original sneakers come in a minimalist, leather silhouette resting on a rubber sole and are finished with the brand's signature coding on the outer sides.",
      price: 279.73,
      brand: "adidas",
      color: "yellow",
      photo: "manshoes14",
      onSale: false,
    },
    {
      id: "ms15",
      title: "green adidas shoes (ms15)",
      desc:
        "The original sneakers come in a minimalist, leather silhouette resting on a rubber sole and are finished with the brand's signature coding on the outer sides.",
      price: 107.18,
      brand: "adidas",
      color: "green",
      photo: "manshoes15",
      onSale: true,
    },
    {
      id: "ms16",
      title: "blue adidas shoes (ms16)",
      desc:
        "The original sneakers come in a minimalist, leather silhouette resting on a rubber sole and are finished with the brand's signature coding on the outer sides.",
      price: 178.48,
      brand: "adidas",
      color: "blue",
      photo: "manshoes16",
      onSale: true,
    },
    {
      id: "ms17",
      title: "blue adidas shoes (ms17)",
      desc:
        "The original sneakers come in a minimalist, leather silhouette resting on a rubber sole and are finished with the brand's signature coding on the outer sides.",
      price: 55.99,
      brand: "adidas",
      color: "blue",
      photo: "manshoes17",
      onSale: false,
    },
    {
      id: "ms18",
      title: "yellow adidas shoes (ms18)",
      desc:
        "The original sneakers come in a minimalist, leather silhouette resting on a rubber sole and are finished with the brand's signature coding on the outer sides.",
      price: 155.73,
      brand: "adidas",
      color: "yellow",
      photo: "manshoes18",
      onSale: false,
    },
  ],
};

export const womanClothes = {
  tshirts: [
    {
      id: "wt1",
      title: "green adidas t-shirt (wt1)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 213.51,
      brand: "adidas",
      color: "green",
      photo: "womanshirt1",
      onSale: false,
    },
    {
      id: "wt2",
      title: "blue adidas t-shirt (wt2)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 48.54,
      brand: "adidas",
      color: "blue",
      photo: "womanshirt2",
      onSale: false,
    },
    {
      id: "wt3",
      title: "blue adidas t-shirt (wt3)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 293.96,
      brand: "adidas",
      color: "blue",
      photo: "womanshirt3",
      onSale: false,
    },
    {
      id: "wt4",
      title: "green adidas t-shirt (wt4)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 142.65,
      brand: "adidas",
      color: "green",
      photo: "womanshirt4",
      onSale: false,
    },
    {
      id: "wt5",
      title: "green adidas t-shirt (wt5)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 37.23,
      brand: "adidas",
      color: "green",
      photo: "womanshirt5",
      onSale: false,
    },
    {
      id: "wt6",
      title: "green adidas t-shirt (wt6)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 291.13,
      brand: "adidas",
      color: "green",
      photo: "womanshirt6",
      onSale: true,
    },
    {
      id: "wt7",
      title: "green adidas t-shirt (wt7)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 39.63,
      brand: "adidas",
      color: "green",
      photo: "womanshirt7",
      onSale: false,
    },
    {
      id: "wt8",
      title: "green reebok t-shirt (wt8)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 74.66,
      brand: "reebok",
      color: "green",
      photo: "womanshirt8",
      onSale: false,
    },
    {
      id: "wt9",
      title: "blue reebok t-shirt (wt9)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 62.81,
      brand: "reebok",
      color: "blue",
      photo: "womanshirt9",
      onSale: true,
    },
    {
      id: "wt10",
      title: "blue reebok t-shirt (wt10)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 235.49,
      brand: "reebok",
      color: "blue",
      photo: "womanshirt10",
      onSale: false,
    },
    {
      id: "wt11",
      title: "yellow reebok t-shirt (wt11)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 41.81,
      brand: "reebok",
      color: "yellow",
      photo: "womanshirt11",
      onSale: false,
    },
    {
      id: "wt12",
      title: "yellow reebok t-shirt (wt12)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 268.35,
      brand: "reebok",
      color: "yellow",
      photo: "womanshirt12",
      onSale: true,
    },
    {
      id: "wt13",
      title: "red reebok t-shirt (wt13)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 251.22,
      brand: "reebok",
      color: "red",
      photo: "womanshirt13",
      onSale: true,
    },
    {
      id: "wt14",
      title: "blue reebok t-shirt (wt14)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 34.96,
      brand: "reebok",
      color: "blue",
      photo: "womanshirt14",
      onSale: false,
    },
    {
      id: "wt15",
      title: "red reebok t-shirt (wt15)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 82.02,
      brand: "reebok",
      color: "red",
      photo: "womanshirt15",
      onSale: false,
    },
    {
      id: "wt16",
      title: "green reebok t-shirt (wt16)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 170.76,
      brand: "reebok",
      color: "green",
      photo: "womanshirt16",
      onSale: false,
    },
    {
      id: "wt17",
      title: "green nike t-shirt (wt17)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 117.59,
      brand: "nike",
      color: "green",
      photo: "womanshirt17",
      onSale: false,
    },
    {
      id: "wt18",
      title: "blue nike t-shirt (wt18)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 41.45,
      brand: "nike",
      color: "blue",
      photo: "womanshirt18",
      onSale: false,
    },
    {
      id: "wt19",
      title: "blue nike t-shirt (wt19)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 58.07,
      brand: "nike",
      color: "blue",
      photo: "womanshirt19",
      onSale: false,
    },
    {
      id: "wt20",
      title: "green nike t-shirt (wt20)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 68.92,
      brand: "nike",
      color: "green",
      photo: "womanshirt20",
      onSale: true,
    },
    {
      id: "wt21",
      title: "green nike t-shirt (wt21)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 143.94,
      brand: "nike",
      color: "green",
      photo: "womanshirt21",
      onSale: false,
    },
    {
      id: "wt22",
      title: "yellow nike t-shirt (wt22)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 213.53,
      brand: "nike",
      color: "yellow",
      photo: "womanshirt22",
      onSale: false,
    },
    {
      id: "wt23",
      title: "red nike t-shirt (wt23)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 272.0,
      brand: "nike",
      color: "red",
      photo: "womanshirt23",
      onSale: false,
    },
    {
      id: "wt24",
      title: "red nike t-shirt (wt24)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 65.69,
      brand: "nike",
      color: "red",
      photo: "womanshirt24",
      onSale: false,
    },
    {
      id: "wt25",
      title: "yellow nike t-shirt (wt25)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 102.99,
      brand: "nike",
      color: "yellow",
      photo: "womanshirt25",
      onSale: false,
    },
    {
      id: "wt26",
      title: "yellow puma t-shirt (wt26)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 96.69,
      brand: "puma",
      color: "yellow",
      photo: "womanshirt26",
      onSale: false,
    },
    {
      id: "wt27",
      title: "blue puma t-shirt (wt27)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 74.26,
      brand: "puma",
      color: "blue",
      photo: "womanshirt27",
      onSale: false,
    },
    {
      id: "wt28",
      title: "blue puma t-shirt (wt28)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 56.37,
      brand: "puma",
      color: "blue",
      photo: "womanshirt28",
      onSale: false,
    },
    {
      id: "wt29",
      title: "yellow puma t-shirt (wt29)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 166.72,
      brand: "puma",
      color: "yellow",
      photo: "womanshirt29",
      onSale: false,
    },
    {
      id: "wt30",
      title: "blue puma t-shirt (wt30)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 210.14,
      brand: "puma",
      color: "blue",
      photo: "womanshirt30",
      onSale: true,
    },
    {
      id: "wt31",
      title: "red puma t-shirt (wt31)",
      desc:
        "The best-fitting and flattering T-shirt. This basic tee especially has just the right weight to make it feel like a real shirt and not something sloppy. This one is not a workout tee per say, but you can't go wrong with one of those options, either.",
      price: 254.78,
      brand: "puma",
      color: "red",
      photo: "womanshirt31",
      onSale: false,
    },
  ],
  pants: [
    {
      id: "wp1",
      title: "red reebok pants (wp1)",
      desc:
        "Featuring a flattering, slim fit, these trousers have just the right amount of stretch in the fabric to avoid feeling like a stuffed sausage. Available in several colorways, you can stock your whole closet with this perfect pant for spring.",
      price: 81.77,
      brand: "reebok",
      color: "red",
      photo: "womanpants1",
      onSale: true,
    },
    {
      id: "wp2",
      title: "red reebok pants (wp2)",
      desc:
        "Featuring a flattering, slim fit, these trousers have just the right amount of stretch in the fabric to avoid feeling like a stuffed sausage. Available in several colorways, you can stock your whole closet with this perfect pant for spring.",
      price: 169.23,
      brand: "reebok",
      color: "red",
      photo: "womanpants2",
      onSale: true,
    },
    {
      id: "wp3",
      title: "green reebok pants (wp3)",
      desc:
        "Featuring a flattering, slim fit, these trousers have just the right amount of stretch in the fabric to avoid feeling like a stuffed sausage. Available in several colorways, you can stock your whole closet with this perfect pant for spring.",
      price: 278.88,
      brand: "reebok",
      color: "green",
      photo: "womanpants3",
      onSale: false,
    },
    {
      id: "wp4",
      title: "blue reebok pants (wp4)",
      desc:
        "Featuring a flattering, slim fit, these trousers have just the right amount of stretch in the fabric to avoid feeling like a stuffed sausage. Available in several colorways, you can stock your whole closet with this perfect pant for spring.",
      price: 129.28,
      brand: "reebok",
      color: "blue",
      photo: "womanpants4",
      onSale: false,
    },
    {
      id: "wp5",
      title: "green reebok pants (wp5)",
      desc:
        "Featuring a flattering, slim fit, these trousers have just the right amount of stretch in the fabric to avoid feeling like a stuffed sausage. Available in several colorways, you can stock your whole closet with this perfect pant for spring.",
      price: 119.87,
      brand: "reebok",
      color: "green",
      photo: "womanpants5",
      onSale: false,
    },
    {
      id: "wp6",
      title: "blue reebok pants (wp6)",
      desc:
        "Featuring a flattering, slim fit, these trousers have just the right amount of stretch in the fabric to avoid feeling like a stuffed sausage. Available in several colorways, you can stock your whole closet with this perfect pant for spring.",
      price: 106.04,
      brand: "reebok",
      color: "blue",
      photo: "womanpants6",
      onSale: true,
    },
    {
      id: "wp7",
      title: "red reebok pants (wp7)",
      desc:
        "Featuring a flattering, slim fit, these trousers have just the right amount of stretch in the fabric to avoid feeling like a stuffed sausage. Available in several colorways, you can stock your whole closet with this perfect pant for spring.",
      price: 217.81,
      brand: "reebok",
      color: "red",
      photo: "womanpants7",
      onSale: false,
    },
    {
      id: "wp8",
      title: "red reebok pants (wp8)",
      desc:
        "Featuring a flattering, slim fit, these trousers have just the right amount of stretch in the fabric to avoid feeling like a stuffed sausage. Available in several colorways, you can stock your whole closet with this perfect pant for spring.",
      price: 115.26,
      brand: "reebok",
      color: "red",
      photo: "womanpants8",
      onSale: true,
    },
    {
      id: "wp9",
      title: "yellow reebok pants (wp9)",
      desc:
        "Featuring a flattering, slim fit, these trousers have just the right amount of stretch in the fabric to avoid feeling like a stuffed sausage. Available in several colorways, you can stock your whole closet with this perfect pant for spring.",
      price: 47.05,
      brand: "reebok",
      color: "yellow",
      photo: "womanpants9",
      onSale: false,
    },
    {
      id: "wp10",
      title: "blue reebok pants (wp10)",
      desc:
        "Featuring a flattering, slim fit, these trousers have just the right amount of stretch in the fabric to avoid feeling like a stuffed sausage. Available in several colorways, you can stock your whole closet with this perfect pant for spring.",
      price: 145.73,
      brand: "reebok",
      color: "blue",
      photo: "womanpants10",
      onSale: false,
    },
    {
      id: "wp11",
      title: "green puma pants (wp11)",
      desc:
        "Featuring a flattering, slim fit, these trousers have just the right amount of stretch in the fabric to avoid feeling like a stuffed sausage. Available in several colorways, you can stock your whole closet with this perfect pant for spring.",
      price: 54.94,
      brand: "puma",
      color: "green",
      photo: "womanpants11",
      onSale: false,
    },
    {
      id: "wp12",
      title: "blue puma pants (wp12)",
      desc:
        "Featuring a flattering, slim fit, these trousers have just the right amount of stretch in the fabric to avoid feeling like a stuffed sausage. Available in several colorways, you can stock your whole closet with this perfect pant for spring.",
      price: 88.61,
      brand: "puma",
      color: "blue",
      photo: "womanpants12",
      onSale: true,
    },
    {
      id: "wp13",
      title: "blue puma pants (wp13)",
      desc:
        "Featuring a flattering, slim fit, these trousers have just the right amount of stretch in the fabric to avoid feeling like a stuffed sausage. Available in several colorways, you can stock your whole closet with this perfect pant for spring.",
      price: 90.23,
      brand: "puma",
      color: "blue",
      photo: "womanpants13",
      onSale: false,
    },
    {
      id: "wp14",
      title: "red puma pants (wp14)",
      desc:
        "Featuring a flattering, slim fit, these trousers have just the right amount of stretch in the fabric to avoid feeling like a stuffed sausage. Available in several colorways, you can stock your whole closet with this perfect pant for spring.",
      price: 198.49,
      brand: "puma",
      color: "red",
      photo: "womanpants14",
      onSale: false,
    },
    {
      id: "wp15",
      title: "red puma pants (wp15)",
      desc:
        "Featuring a flattering, slim fit, these trousers have just the right amount of stretch in the fabric to avoid feeling like a stuffed sausage. Available in several colorways, you can stock your whole closet with this perfect pant for spring.",
      price: 280.05,
      brand: "puma",
      color: "red",
      photo: "womanpants15",
      onSale: false,
    },
    {
      id: "wp16",
      title: "green puma pants (wp16)",
      desc:
        "Featuring a flattering, slim fit, these trousers have just the right amount of stretch in the fabric to avoid feeling like a stuffed sausage. Available in several colorways, you can stock your whole closet with this perfect pant for spring.",
      price: 221.18,
      brand: "puma",
      color: "green",
      photo: "womanpants16",
      onSale: false,
    },
    {
      id: "wp17",
      title: "green nike pants (wp17)",
      desc:
        "Featuring a flattering, slim fit, these trousers have just the right amount of stretch in the fabric to avoid feeling like a stuffed sausage. Available in several colorways, you can stock your whole closet with this perfect pant for spring.",
      price: 54.97,
      brand: "nike",
      color: "green",
      photo: "womanpants17",
      onSale: false,
    },
    {
      id: "wp18",
      title: "blue nike pants (wp18)",
      desc:
        "Featuring a flattering, slim fit, these trousers have just the right amount of stretch in the fabric to avoid feeling like a stuffed sausage. Available in several colorways, you can stock your whole closet with this perfect pant for spring.",
      price: 256.64,
      brand: "nike",
      color: "blue",
      photo: "womanpants18",
      onSale: false,
    },
    {
      id: "wp19",
      title: "blue nike pants (wp19)",
      desc:
        "Featuring a flattering, slim fit, these trousers have just the right amount of stretch in the fabric to avoid feeling like a stuffed sausage. Available in several colorways, you can stock your whole closet with this perfect pant for spring.",
      price: 136.49,
      brand: "nike",
      color: "blue",
      photo: "womanpants19",
      onSale: false,
    },
    {
      id: "wp20",
      title: "yellow nike pants (wp20)",
      desc:
        "Featuring a flattering, slim fit, these trousers have just the right amount of stretch in the fabric to avoid feeling like a stuffed sausage. Available in several colorways, you can stock your whole closet with this perfect pant for spring.",
      price: 296.63,
      brand: "nike",
      color: "yellow",
      photo: "womanpants20",
      onSale: false,
    },
    {
      id: "wp21",
      title: "yellow adidas pants (wp21)",
      desc:
        "Featuring a flattering, slim fit, these trousers have just the right amount of stretch in the fabric to avoid feeling like a stuffed sausage. Available in several colorways, you can stock your whole closet with this perfect pant for spring.",
      price: 177.68,
      brand: "adidas",
      color: "yellow",
      photo: "womanpants21",
      onSale: false,
    },
  ],
  shoes: [
    {
      id: "ws1",
      title: "yellow adidas shoes (ws1)",
      desc:
        "The original sneakers come in a minimalist, leather silhouette resting on a rubber sole and are finished with the brand's signature coding on the outer sides.",
      price: 68.17,
      brand: "adidas",
      color: "yellow",
      photo: "womanshoes1",
      onSale: false,
    },
    {
      id: "ws2",
      title: "green adidas shoes (ws2)",
      desc:
        "The original sneakers come in a minimalist, leather silhouette resting on a rubber sole and are finished with the brand's signature coding on the outer sides.",
      price: 51.63,
      brand: "adidas",
      color: "green",
      photo: "womanshoes2",
      onSale: false,
    },
    {
      id: "ws3",
      title: "blue adidas shoes (ws3)",
      desc:
        "The original sneakers come in a minimalist, leather silhouette resting on a rubber sole and are finished with the brand's signature coding on the outer sides.",
      price: 48.73,
      brand: "adidas",
      color: "blue",
      photo: "womanshoes3",
      onSale: true,
    },
    {
      id: "ws4",
      title: "red adidas shoes (ws4)",
      desc:
        "The original sneakers come in a minimalist, leather silhouette resting on a rubber sole and are finished with the brand's signature coding on the outer sides.",
      price: 248.66,
      brand: "adidas",
      color: "red",
      photo: "womanshoes4",
      onSale: false,
    },
    {
      id: "ws5",
      title: "blue adidas shoes (ws5)",
      desc:
        "The original sneakers come in a minimalist, leather silhouette resting on a rubber sole and are finished with the brand's signature coding on the outer sides.",
      price: 205.54,
      brand: "adidas",
      color: "blue",
      photo: "womanshoes5",
      onSale: true,
    },
    {
      id: "ws6",
      title: "green adidas shoes (ws6)",
      desc:
        "The original sneakers come in a minimalist, leather silhouette resting on a rubber sole and are finished with the brand's signature coding on the outer sides.",
      price: 111.76,
      brand: "adidas",
      color: "green",
      photo: "womanshoes6",
      onSale: false,
    },
    {
      id: "ws7",
      title: "green reebok shoes (ws7)",
      desc:
        "The original sneakers come in a minimalist, leather silhouette resting on a rubber sole and are finished with the brand's signature coding on the outer sides.",
      price: 157.99,
      brand: "reebok",
      color: "green",
      photo: "womanshoes7",
      onSale: false,
    },
    {
      id: "ws8",
      title: "blue reebok shoes (ws8)",
      desc:
        "The original sneakers come in a minimalist, leather silhouette resting on a rubber sole and are finished with the brand's signature coding on the outer sides.",
      price: 263.37,
      brand: "reebok",
      color: "blue",
      photo: "womanshoes8",
      onSale: false,
    },
    {
      id: "ws9",
      title: "blue reebok shoes (ws9)",
      desc:
        "The original sneakers come in a minimalist, leather silhouette resting on a rubber sole and are finished with the brand's signature coding on the outer sides.",
      price: 174.34,
      brand: "reebok",
      color: "blue",
      photo: "womanshoes9",
      onSale: false,
    },
    {
      id: "ws10",
      title: "yellow reebok shoes (ws10)",
      desc:
        "The original sneakers come in a minimalist, leather silhouette resting on a rubber sole and are finished with the brand's signature coding on the outer sides.",
      price: 219.55,
      brand: "reebok",
      color: "yellow",
      photo: "womanshoes10",
      onSale: false,
    },
    {
      id: "ws11",
      title: "red reebok shoes (ws11)",
      desc:
        "The original sneakers come in a minimalist, leather silhouette resting on a rubber sole and are finished with the brand's signature coding on the outer sides.",
      price: 298.59,
      brand: "reebok",
      color: "red",
      photo: "womanshoes11",
      onSale: false,
    },
    {
      id: "ws12",
      title: "red reebok shoes (ws12)",
      desc:
        "The original sneakers come in a minimalist, leather silhouette resting on a rubber sole and are finished with the brand's signature coding on the outer sides.",
      price: 63.49,
      brand: "reebok",
      color: "red",
      photo: "womanshoes12",
      onSale: false,
    },
    {
      id: "ws13",
      title: "red nike shoes (ws13)",
      desc:
        "The original sneakers come in a minimalist, leather silhouette resting on a rubber sole and are finished with the brand's signature coding on the outer sides.",
      price: 197.14,
      brand: "nike",
      color: "red",
      photo: "womanshoes13",
      onSale: false,
    },
    {
      id: "ws14",
      title: "green nike shoes (ws14)",
      desc:
        "The original sneakers come in a minimalist, leather silhouette resting on a rubber sole and are finished with the brand's signature coding on the outer sides.",
      price: 108.56,
      brand: "nike",
      color: "green",
      photo: "womanshoes14",
      onSale: false,
    },
    {
      id: "ws15",
      title: "green nike shoes (ws15)",
      desc:
        "The original sneakers come in a minimalist, leather silhouette resting on a rubber sole and are finished with the brand's signature coding on the outer sides.",
      price: 101.33,
      brand: "nike",
      color: "green",
      photo: "womanshoes15",
      onSale: false,
    },
    {
      id: "ws16",
      title: "green nike shoes (ws16)",
      desc:
        "The original sneakers come in a minimalist, leather silhouette resting on a rubber sole and are finished with the brand's signature coding on the outer sides.",
      price: 105.45,
      brand: "nike",
      color: "green",
      photo: "womanshoes16",
      onSale: false,
    },
    {
      id: "ws17",
      title: "blue nike shoes (ws17)",
      desc:
        "The original sneakers come in a minimalist, leather silhouette resting on a rubber sole and are finished with the brand's signature coding on the outer sides.",
      price: 178.89,
      brand: "nike",
      color: "blue",
      photo: "womanshoes17",
      onSale: false,
    },
    {
      id: "ws18",
      title: "red nike shoes (ws18)",
      desc:
        "The original sneakers come in a minimalist, leather silhouette resting on a rubber sole and are finished with the brand's signature coding on the outer sides.",
      price: 100.25,
      brand: "nike",
      color: "red",
      photo: "womanshoes18",
      onSale: false,
    },
    {
      id: "ws19",
      title: "green puma shoes (ws19)",
      desc:
        "The original sneakers come in a minimalist, leather silhouette resting on a rubber sole and are finished with the brand's signature coding on the outer sides.",
      price: 282.39,
      brand: "puma",
      color: "green",
      photo: "womanshoes19",
      onSale: true,
    },
    {
      id: "ws20",
      title: "blue puma shoes (ws20)",
      desc:
        "The original sneakers come in a minimalist, leather silhouette resting on a rubber sole and are finished with the brand's signature coding on the outer sides.",
      price: 249.18,
      brand: "puma",
      color: "blue",
      photo: "womanshoes20",
      onSale: false,
    },
    {
      id: "ws21",
      title: "yellow puma shoes (ws21)",
      desc:
        "The original sneakers come in a minimalist, leather silhouette resting on a rubber sole and are finished with the brand's signature coding on the outer sides.",
      price: 209.05,
      brand: "puma",
      color: "yellow",
      photo: "womanshoes21",
      onSale: false,
    },
    {
      id: "ws22",
      title: "yellow puma shoes (ws22)",
      desc:
        "The original sneakers come in a minimalist, leather silhouette resting on a rubber sole and are finished with the brand's signature coding on the outer sides.",
      price: 158.19,
      brand: "puma",
      color: "yellow",
      photo: "womanshoes22",
      onSale: false,
    },
    {
      id: "ws23",
      title: "green puma shoes (ws23)",
      desc:
        "The original sneakers come in a minimalist, leather silhouette resting on a rubber sole and are finished with the brand's signature coding on the outer sides.",
      price: 180.92,
      brand: "puma",
      color: "green",
      photo: "womanshoes23",
      onSale: false,
    },
    {
      id: "ws24",
      title: "blue puma shoes (ws24)",
      desc:
        "The original sneakers come in a minimalist, leather silhouette resting on a rubber sole and are finished with the brand's signature coding on the outer sides.",
      price: 52.04,
      brand: "puma",
      color: "blue",
      photo: "womanshoes24",
      onSale: false,
    },
    {
      id: "ws25",
      title: "red puma shoes (ws25)",
      desc:
        "The original sneakers come in a minimalist, leather silhouette resting on a rubber sole and are finished with the brand's signature coding on the outer sides.",
      price: 187.0,
      brand: "puma",
      color: "red",
      photo: "womanshoes25",
      onSale: false,
    },
    {
      id: "ws26",
      title: "blue puma shoes (ws26)",
      desc:
        "The original sneakers come in a minimalist, leather silhouette resting on a rubber sole and are finished with the brand's signature coding on the outer sides.",
      price: 226.37,
      brand: "puma",
      color: "blue",
      photo: "womanshoes26",
      onSale: false,
    },
    {
      id: "ws27",
      title: "red puma shoes (ws27)",
      desc:
        "The original sneakers come in a minimalist, leather silhouette resting on a rubber sole and are finished with the brand's signature coding on the outer sides.",
      price: 185.34,
      brand: "puma",
      color: "red",
      photo: "womanshoes27",
      onSale: true,
    },
  ],
};
